---
name: nimlsp
description: The Nim language server implementation (based on nimsuggest)
homepage: https://github.com/nim-lang/langserver
licenses:
  - MIT
languages:
  - Nim
categories:
  - LSP

source:
  # renovate:datasource=github-tags
  id: pkg:github/nim-lang/langserver@latest
  build:
    - target: unix
      run: nimble build -y --localdeps
      bin: nimlangserver
    - target: win
      run: nimble build -y --localdeps
      bin: nimlangserver.exe

bin:
  nimlsp: "{{source.build.bin}}"
